FROM rustlang/rust:nightly

RUN cargo install diesel_cli --no-default-features --features postgres

RUN cargo install cargo-watch

WORKDIR /usr/src/app

EXPOSE 8888

VOLUME ["/usr/local/cargo"]

# ENTRYPOINT ["./entrypoint.sh"]

CMD ["diesel", "setup", "&&", "cargo", "watch", "-x", "run"]
